#!/bin/bash

spark_args_small="spark.cores.max=64 spark.executor.memory=8g spark.driver.memory=8g spark.executor.cores=2"
spark_args_medium="spark.cores.max=128 spark.executor.memory=16g spark.driver.memory=16g spark.executor.cores=4"
spark_args_large="spark.cores.max=256 spark.executor.memory=32g spark.driver.memory=32g spark.executor.cores=8"
spark_args=$spark_args_small
dry_run_option=""
feature_config=""
checkpoint_option=""
start_date=$(date +%Y-%m-%d)
end_date=$(date +%Y-%m-%d)

while getopts ":r:csmldf:-:" arg; do
    case "${arg}" in
        c)
            checkpoint_option="--checkpoint"
            ;;
        s)
            spark_args=$spark_args_small
            ;;
        m)
            spark_args=$spark_args_medium
            ;;
        l)
            spark_args=$spark_args_large
            ;;
        f)
            feature_config="/code/"${OPTARG}
            ;;
        d)
            dry_run_option="--dry-run"
            ;;
        r)
            start_date="${OPTARG}"
            end_date="${OPTARG}"
            ;;
        -)
            case "${OPTARG}" in
                start-date)
                    start_date="${!OPTIND}"; OPTIND=$(( $OPTIND + 1 ))
                    ;;
                end-date)
                    end_date="${!OPTIND}"; OPTIND=$(( $OPTIND + 1 ))
                    ;;
                *)
                    exit 1
                    ;;
            esac;;

        *)
            exit 1
            ;;
    esac
done
shift $((OPTIND -1))

if [ -z "$feature_config" ] ; then
    echo "You must specify a feature config with -f"
    exit 1;
fi

echo "spark-args:" $spark_args
echo "feature_config:" $feature_config
echo "start-date:" $start_date
echo "end-date:" $end_date
echo

paasta_command="paasta spark-run \
    --cluster pnw-prod \
    --pool batch \
    --service business_reporting \
    --instance batch \
    --aws-credentials-yaml /etc/boto_cfg/business_reporting.yaml \
    --aws-region us-west-2 \
    --spark-args \"$spark_args\" \
    --cmd \" \
        spark-submit /code/virtualenv_run/lib/python3.7/site-packages/spark_etl/spark_etl_runner.py \
        --notify-email biz-multiloc-rep+alerts@yelp.com \
        --feature-config $feature_config \
        --start-date $start_date \
        --end-date $end_date \
        --team-name biz-multiloc-rep \
        --no-notification \
        --publish-path s3a://yelp-biz-stats-us-west-2/dev/$(whoami)/ \
        --scratch-path s3a://yelp-biz-stats-us-west-2/dev/scratch/$(whoami)/ \
        $dry_run_option \
        $checkpoint_option \
    \""
echo $paasta_command
